### ISSUE TITLE
Problems with admin/invoice.php

### ISSUE THREAD

**Issue by dbltoe** [mc12345678/Stock_By_Attributes_Combined#100]
First of all, the current file in this github is dated 2020-07-03 and the file in the latest distribution is dated 2020-10-28  with a change done for 1.5.7a on line 182.  In merging the files, I left the change by DrByte and focused only on the Change 1 of 2 and 2 of 2.

When accessing any invoice from the admin, we get the following error:

`[13-Apr-2021 08:51:05 US/Central] PHP Parse error: syntax error, unexpected '}' in /********/invoice.php on line 213

[13-Apr-2021 08:51:05 US/Central] Request URI: /********/index.php?cmd=invoice&oID=65846, IP address: 67.253.65.245
--> PHP Parse error: syntax error, unexpected '}' in /********/invoice.php on line 213.`

**Comment by mc12345678** [comment]
In this code:
````php
                            if ($custom_id != '') {
                              $attribute_name .= ' (' . $customid . ') '
                            }
````
There is a semi-colon missing from the end of that second line (line 212 in your fileset).
The code should be:
````diff
                            if ($custom_id != '') {
-                              $attribute_name .= ' (' . $customid . ') '
+                              $attribute_name .= ' (' . $customid . ') ';
                            }
````

**Comment by dbltoe** [comment]
That's line 214 of the file you provide and it works now.

THANX

**Comment by mc12345678** [comment]
As of Zen Cart 1.5.7, the above file `admin/invoice.php` is no longer edited/modified. Interaction is provided via observer code.

Any other related information to address in this issue?

**Comment by mc12345678** [comment]
Closing this issue as 45724f4 ("Delete admin files that do not need edit.", 2021-04-15) removed the file in question with insertion of customid information covered by observer operations that capture the customid.
