### ISSUE TITLE
Upgrade does not work due to sql error

### ISSUE THREAD

**Issue by cstdenis** [mc12345678/Stock_By_Attributes_Combined#105]
--> PHP Fatal error: 1062:Duplicate entry 'STOCK_SBA_CUSTOMID_UNIQUE' for key 'unq_config_key_zen' :: INSERT INTO `configuration` (configuration_title, configuration_key, configuration_value,
...

````
--- ./stock_by_attr_install.php.old     2022-02-16 00:47:14.363939000 -0800
+++ ./stock_by_attr_install.php 2022-02-16 00:45:44.158243000 -0800
@@ -201,6 +201,7 @@
     'ATTRIBUTES_SBA_DISPLAY_CUSTOMID',
     'SBA_SHOW_OUT_OF_STOCK_ATTR_ON_PRODUCT_INFO',
     'STOCK_SBA_CUSTOM_FOR_MODEL',
+    'STOCK_SBA_CUSTOMID_UNIQUE',
   );

   foreach ($delete_confs as $delete_conf) {
````

**Comment by mc12345678** [comment]
Thank you for reporting this.

FYI (e.g. "future readers"), I have reviewed the above (though haven't tested on my local install). For information/tracking in response to this I considered making the insert steps of the install/upgrade `INSERT IGNORE`; however, the existing process of operation is to remove previous and (re-)add the new. Therefore, while it would be easier to maintain by using `INSERT IGNORE`, the proper way to maintain this package is to ensure the operations perform what is expected: delete keys that are to be installed by the package.

This process may always be changed in the future, but should be done purposefully, not just to prevent reporting of something missed in the base code.
