### ISSUE TITLE
Step 3 of 3 - Order Confirmation has no confirmation button to proceed

### ISSUE THREAD

**Issue by jodeantn** [mc12345678/Stock_By_Attributes_Combined#43]
Just installed Stock By Attributes Combined for my 1.5.5 fresh install. So far everything works with one exception. The third checkout screen does not have button to proceed beyond Step 3 of 3 of the order checkout process. 

Do you have any clues where I might have gone wrong in the installation?

I am getting the following error:
PHP Fatal error: Call to undefined method payment::process_form_params() in /home/tennes60/public_html/includes/templates/tennessee_traditional_flies/templates/tpl_checkout_confirmation_default.php on line 205

Line 205   echo zen_draw_form('checkout_confirmation', $form_action_url, 'post', 'id="checkout_confirmation" onsubmit="submitonce();"' . (is_array($payment_modules->modules) ? $payment_modules->process_form_params() : ''));

Url http://tennesseetraditionalflies.com/index.php?main_page=checkout_confirmation

This is coming from a fresh install Stock_By_Attributes_combined-master/1_5_5/includes/templates/YOUR_TEMPLATE/templates tpl_checkout_confirmation_default.php

I tried the Stock_By_Attributes_combined-master/1_5_3 and 1_5_4/includes/templates/YOUR_TEMPLATE/templates tpl_checkout_confirmation_default.php and it does not error.

However the 1_5_3 and 1_5_4 version is probably missing some 1_5_5 code?

**Comment by mc12345678** [comment]
I guess I got ahead of myself introducing that "line" of code into the confirmation page. That code comes from an alternate code modification that was proposed to the ZC team to better support PayPal Incontext with the intent of it being implemented in ZC 1.5.5. 

The portion `. (is_array($payment_modules->modules) ? $payment_modules->process_form_params() : '')` can be omitted from that page. 

I will be updating the code to remove that "line" seeing that it did not get incorporated into 1.5.5 as desired.

On the other side, understand that the file is provided with the intent to be merged with either the current template override version of the file to incorporate the part(s) directly associated with SBA. That other code area should be stated or obvious. It is apparent that that addition was not made clear, and in the long/short of it, it is unrelated to SBA. Still need to make a change to remove that excess code. (maybe it will make it into the next change.)

**Comment by jodeantn** [comment]
The below was edited to remove things like the associated email address, the phone number and related unsubscribe links to maybe minimize any unwanted/undesirable inquiries or effects to your account.  It was for no other reason.
-------
Thanks for your rapid response. You Stock By Attributes is a must have for my small shop. Excellent plugin. It should be embedded in the basic design of the product.

 

I hope in some little way I have helped in the debugging of the current version.

 

Tennessee Traditional Flies

228 Norfolk Ln

Nolensville, TN 37135

Website  <http://tennesseetraditionalflies.com/> http://tennesseetraditionalflies.com/

Facebook  <https://www.facebook.com/Tennessee-Traditional-Flies-173764909345309/?fref=ts> https://www.facebook.com/Tennessee-Traditional-Flies-173764909345309/?fref=ts

Joel Dean Owner

**Comment by mc12345678** [comment]
Find a problem, report a problem, thank you for pointing it out.  Your assistance in that matter certainly has helped and I've even posted the fix in the forum.  Fortunately only applicable to those downloading between December 18th and today. 

As said, I was a little ahead of myself but didn't want users to miss out on the opportunity of the added benefit of the InContext option of PayPal that was furthered a week before the identified code change.

Again, thank you!

As to incorporation, well, there's still several parts/aspects to it that need "improvement". Some of them may just be as I refer to them in some places, bells and whistles, but there remains action to take with it to further it along.  At least it is finally where it has always been described: to be able to handle both single and multiple attribute product.  That hasn't been easy while trying to maintain the flexibility that potteryhouse set out to implement and from review of a commercial version's description doesn't even appear to consider.

There have been minor things that have made it easier to implement thanks to the ZC core team adding some very helpful/well placed notifiers.  As you may have also seen in comparison of the earlier versions of the modified ZC files to those of ZC 1.5.5, the number of applicable/necessary edits has gone down dramatically.  If I can get some time to work out a better display of the customid, then those should go down even further/become smaller.
