### ISSUE TITLE
Attribute drop-down not displaying

### ISSUE THREAD

**Issue by jeking928** [mc12345678/Stock_By_Attributes_Combined#9]
I've upgraded a site from ZC 1.5.4 to 1.5.5 and SBA. The site only uses a single attribute per product. When I change the Option Type from _Dropdown_ to  _SBA Select List (Dropdown) Basic_, the attribute no longer displays.  No error log. I've double checked the installation.
- Admin>Dynamic Drop Downs has been left at the default settings.
- SBA>File Check reports no errors [other than previously noted false positive of /includes/modules/pages/checkout_success/header_php_sba.php]

Do I need to do something other than change the Option Type?

When left as _Dropdown_ the only issue is that an _out of stock_ attribute is not marked as such. The rest of the functionality seems to be just fine.

**Comment by mc12345678** [comment]
There should be no other action required; however, perform the following checks.
While in option names manager, located the value for the sba specific dropdown while viewing the source code of the page.
Goto the configuration menu and select any configuration.
Modify the url to have gID=6
Review the listing to validate the numeric value for the SBA listing is the same as above.

After that, there are three files at play in a standard ZC install for this aspect.
1) Includes/modules/YOUR_TEMPLATE/attributes.php
2) Includes/templates/YOUR_TEMPLATE/templates/tpl_modules_attributes.php
3) Includes/classes/observers/class.products_with_attributes_stock.php (I think that's the filename, going by memory)

A question though is if SBA had previously been installed to the older system and also to please report the discrepancy in the number from above as it may be the culprit and how the new option type number was generated.

**Comment by jeking928** [comment]
> Modify the url to have gID=6
> Review the listing to validate the numeric value for the SBA listing is the same as above.

I see no reference to SBA on this page. To be clear, what title am I looking for?

The three files you mention are all in place.

**Comment by mc12345678** [comment]
`Selection list product option type (SBA)
Please make any necessary changes

Selection list product option type (SBA)
Numeric value of the radio button product option type
`

Above is the "full" info from within the directions provided above.

But, looking at that portion of the install, there may be some issues. Doesn't seem to follow a very logical sequence to address all conditions.

**Comment by jeking928** [comment]
Those options do not exist. Would it be worth running any of the other installation scripts?

**Comment by mc12345678** [comment]
Don't/didn't see another option that would make it work "separately". Have looked back in history of the file even as far back as SBA 1.5.3, there may have been a change that affected the install, but this is the first report of it. It does appear to need modification. In the below, substitute the number as discovered (but not reported) above when viewing the source code on the options name page and place in the tools->Install SQL Patches window of the ZC admin.

```
INSERT INTO configuration (configuration_title, configuration_key, configuration_value,
configuration_description, configuration_group_id, sort_order, date_added)
VALUES
('Selection list product option type (SBA)', 'PRODUCTS_OPTIONS_TYPE_SELECT_SBA', 6, 
 'Numeric value of the radio button product option type',
 '6', 0, now());

```

**Comment by jeking928** [comment]
I'm not clear on what numeric value I'm looking for and where to find it, sorry.

**Comment by mc12345678** [comment]
While on the option names page, "right-click" view source for the page. Search on: SBA Select List (Dropdown) Basic or one of the option name types that is not currently used on the page, such as checkbox, or radio. In the code you should see something like:
`<option value="x" >SBA Select List (Dropdown) Basic` the value x is the number of interest. The first occurrence of 6 in the above sql.

**Comment by jeking928** [comment]
Got it, thanks. It is actually 6:
<option value="6">SBA Select List (Dropdown) Basic</option>

I ran the SQL statement and voila! The drop-down appears on the product page with the proper out of stock notification. I'll do further testing to confirm other functionality.

Is there anything else I can do or provide to see why this happened in the first place?

**Comment by mc12345678** [comment]
Fwiw, for the longest time I have thought there was something wrong with the section of code that generates the key in the configuration table, but it has always "worked out" somehow. When I get in again I'll be changing the function to be more dependable.

**Comment by mc12345678** [comment]
Welcome to look at the install file,  search for '6' the area there is the one in question/an issue.  Thinking I modified it a long time ago "for the better" but only half so. Something about how it was modified tells me that I was trying to also keep things the same...

Of course one of the other improvements is to incorporate an additional add/remove option just for that product type...

**Comment by jeking928** [comment]
Ha! If it ain't broke, don't fix it works until it doesn't work any more.

mc12345678 wrote:

**Comment by mc12345678** [comment]
> Ha! If it ain't broke, don't fix it works until it doesn't work any more.

Well... Perhaps that section worked, but I was a bit concerned about the software passing through the stringent ZC reviewer(s) requirements... The more "zen" something becomes the more acceptable and less likely to have to go through the submission process again... Trust me, once through that process for a single app is enough. I saw you submitted an updated CEON, I was going to take a look at it as well here soon.

**Comment by mc12345678** [comment]
Issue ought to be corrected in commit 203383a8111f51a4c28dcecd8b0b3a07b57320c9.  This is on the branch: https://github.com/mc12345678/Stock_by_Attributes_Combined/tree/grid-attributes-observer which for the time being is more about current SBA related improvements than it is about using grid attributes as that plugin (available from ZC forum) has been updated to function with ZC 1.5.3+ and SBA and is being maintained independent of SBA.

**Comment by jeking928** [comment]
Very cool. I have a site I manage pro bono for a dog rescue that I can 
try this on.

mc12345678 wrote:

**Comment by mc12345678** [comment]
Me too. Maybe one day soon will finish the adoption product type that I've been working on and submit as a plugin. Need to work through a couple more things in addition to integrating with the forthcoming upgrade.

Realize this is a sidebar, but, product type offers five "phases": available, adopted, rainbow bridge, hospice, and an "info" or hidden option. Additional data associated with it is age of dog, duration in rescue, age at passing, cut-off points of when a dog can be shown on the website (minimum age), storage of text for each of the above phases so can reference one while writing another, storage of "private" data such as who is caring for the dog, other data as "needed". Was an original idea when our site was only a website, but transitioned the code over to ZC in order to support the site becoming full Zen.

**Comment by jeking928** [comment]
I didn't know you did any work with dog rescue...or did I just forget? 
What is the url?

mc12345678 wrote:

**Comment by mc12345678** [comment]
Don't recall a discussion about it myself. Check your ZC PMs.

**Comment by mc12345678** [comment]
Incorporated into the master branch.  Closing this issue.
