### ISSUE TITLE
Icon image suggestion

### ISSUE THREAD

**Issue by drbyte** [mc12345678/Stock_By_Attributes_Combined#96]
> <a  ... href="<?php echo zen_href_link(FILENAME_PRODUCTS_WITH_ATTRIBUTES_STOCK, '', 'NONSSL') ?>" target="_blank">
<?php /* mc12345678 Need an appropriate picture/statement for the goto SBA information here. */ 
echo zen_image_button('button_sba_link.gif', IMAGE_OPTION_SBA); ?>
</a>

Since 1.5.7 has FontAwesome integrated, and since 1.5.7 now has a notifier hook for inserting these menu items,
I would suggest using a FontAwesome icon instead of calling zen_image_button().

`<i class="fa fa-share-square-o" aria-hidden="true"></i>` is probably adequate: the arrow denotes jumping to another page, which clicking this item does.

**Comment by mc12345678** [comment]
Noting that this one calls for fa-share-square-o, I prefer the suggestion of #97.  Closing this issue to shortly have the other closed by incorporation.
